services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ivetranotask$default
      MYSQL_ROOT_PASSWORD: tasks123
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql